### ISSUE TITLE
Update Social Sharing Image for Repo

### ISSUE THREAD

**Issue by splatyourbugs** [BugSplat-Git/bugsplat-unity#61]
**Note that I have a different file for this one that mentions game developers specifically,**

Follow these instructions for this repo to add social sharing image - [https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview)

Social image for github. 
![bugsplat-github-social-sharable-game-dev](https://user-images.githubusercontent.com/20464226/149042285-414b9153-258f-44bf-a641-913d1553f27c.png)

**Comment by bobbyg603** [comment]
Done!
